<a href="https://colab.research.google.com/github/thoufiqz55/Pytorch/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Basics: Tensors & Gradients

### Part 1 of "Deep Learning with Pytorch"

PyTorch is an open source machine learning framework based on the Torch library,PyTorch defines a class called Tensor (torch.Tensor) to store and operate on homogeneous multidimensional rectangular arrays of numbers. PyTorch Tensors are similar to NumPy Arrays, but can also be operated on a CUDA-capable NVIDIA GPU. PyTorch has also been developing support for other GPU platforms, for example, AMD's ROCm and Apple's Metal Framework.

PyTorch supports various sub-types of Tensors.

This tutorial series is a hands-on beginner-friendly introduction to deep learning using [PyTorch](https://pytorch.org), an open-source neural networks library. These tutorials take a practical and coding-focused approach. The best way to learn the material is to execute the code and experiment with it yourself. Check out the full series here:



This tutorial covers the following topics:

* Introductions to PyTorch tensors
* Tensor operations and gradients
* Interoperability between PyTorch and Numpy
* How to use the PyTorch documentation site

## Prerequisites
If you're just getting started with data science and deep learning, then this tutorial series is for you. You just need to know the following:

Basic Programming with Python (variables, data types, loops, functions etc.)
Some high school mathematics (vectors, matrices, derivatives and probability)
No prior knowledge of data science or deep learning is required
We'll cover any additional mathematical and theoretical concepts we need as we go along.

Let's import the torch module to get started.

In [ ]:
import torch

## Tensors
At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.

In [ ]:
# Number
a1 = torch.tensor(4.)
a1

tensor(4.)

4. is a shorthand for 4.0. It is used to indicate to Python (and PyTorch) that you want to create a floating-point number. We can verify this by checking the dtype attribute of our tensor.

In [ ]:
a1.dtype

torch.float32

Let's try creating more coplex tensors

In [ ]:
# Vector
a2 = torch.tensor([1.,2,3,4])
a2

tensor([1., 2., 3., 4.])

In [ ]:
# Matrix
a3 = torch.tensor([[5.,6],
                  [7,8],
                  [9,10]])
a3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
# 3-dimensional array
a4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
a4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

Tensors can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the .shape property of a tensor.

In [ ]:
print(a1)
a1.shape

tensor(4.)


torch.Size([])

In [ ]:
print(a2)
a2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [ ]:
print(a3)
a3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [ ]:
print(a4)
a4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

Note that it's not possible to create tensors with an improper shape.

In [ ]:
# Matrix
a5 = torch.tensor([[4., 5, 10], 
                   [6, 7], 
                   [8, 9]])
a5

ValueError: ignored

A ValueError is thrown because the lengths of the rows [4., 5, 10] and [6, 7] don't match.


## Tensor operations and gradients
We can combine tensors with the usual arithmetic operations. Let's look at an example:

In [ ]:
# Create tensors.
x = torch.tensor(3.)
y = torch.tensor(4., requires_grad=True)
z = torch.tensor(5., requires_grad=True)
x, y, z

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created three tensors: x, y, and z, all numbers. y and z have an additional parameter requires_grad set to True. We'll see what it does in just a moment.

Let's create a new tensor v by combining these tensors.

In [ ]:
# Arithmetic operations
v = y * x + z
v

tensor(17., grad_fn=<AddBackward0>)

As expected, y is a tensor with the value 3 * 4 + 5 = 17. What makes PyTorch unique is that we can automatically compute the derivative of v w.r.t. the tensors that have requires_grad set to True i.e. y and z. This feature of PyTorch is called autograd (automatic gradients).

To compute the derivatives, we can invoke the .backward method on our result v.

In [ ]:
# Compute derivatives
v.backward()

The derivatives of v with respect to the input tensors are stored in the .grad property of the respective tensors.

In [ ]:
# Display gradients
print('dv/dx:', x.grad)
print('dv/dy:', y.grad)
print('dv/dz:', z.grad)

dv/dx: None
dv/dy: tensor(3.)
dv/dz: tensor(1.)


As expected, dv/dy has the same value as x, i.e., 3, and dv/dz has the value 1. Note that x.grad is None because x doesn't have requires_grad set to True.

The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient is primarily used while dealing with vectors and matrices.

## Tensor functions
Apart from arithmetic operations, the torch module also contains many functions for creating and manipulating tensors. Let's look at some examples.

In [ ]:
# Create a tensor with a fixed value for every element
a6 = torch.full((3, 2), 32)
a6

tensor([[32, 32],
        [32, 32],
        [32, 32]])

In [ ]:
# Concatenate two tensors with compatible shapes
a7 = torch.cat((a3, a6))
a7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [32., 32.],
        [32., 32.],
        [32., 32.]])

In [ ]:
# Compute the sin of each element
a8 = torch.sin(a7)
a8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [ 0.5514,  0.5514],
        [ 0.5514,  0.5514],
        [ 0.5514,  0.5514]])

In [ ]:
# Change the shape of a tensor
a9 = a8.reshape(3, 2, 2)
a9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [ 0.5514,  0.5514]],

        [[ 0.5514,  0.5514],
         [ 0.5514,  0.5514]]])

## Interoperability with Numpy

[Numpy](http://www.numpy.org/) is a popular open-source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays and has a vast ecosystem of supporting libraries, including:

* [Pandas](https://pandas.pydata.org/) for file I/O and data analysis
* [Matplotlib](https://matplotlib.org/) for plotting and visualization
* [OpenCV](https://opencv.org/) for image and video processing

Here's how we create an array in Numpy:

In [ ]:
import numpy as np

x = np.array([[4, 5.], [6, 7]])
x

array([[4., 5.],
       [6., 7.]])

We can convert a Numpy array to a PyTorch tensor using torch.from_numpy.

In [ ]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[4., 5.],
        [6., 7.]], dtype=torch.float64)

Let's verify that the numpy array and torch tensor have similar data types.

In [ ]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert a PyTorch tensor to a Numpy array using the .numpy method of a tensor.

In [ ]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[4., 5.],
       [6., 7.]])

The interoperability between PyTorch and Numpy is essential because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

You might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

1. **Autograd**: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
2. **GPU support**: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.
We'll leverage both these features of PyTorch extensively in this tutorial series.